included:
  - Sources
  - Tests
excluded:
  - .build
  - Package.swift

disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast
  - force_try
  - identifier_name
  - type_name

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
