import Foundation

public enum FlavorQuotePacks {
    public static func pack(for profile: AppProfile) -> [FlavorLine] {
        switch profile {
        case .standard:
            return standard
        case .canadian:
            return canadian
        case .aussie:
            return aussie
        }
    }

    public static let standard: [FlavorLine] = [
        FlavorLine("I heard you. Regrettably."),
        FlavorLine("That was acceptable. Don't make it a pattern."),
        FlavorLine("Dictation complete. Try less chaos next time."),
        FlavorLine("You spoke. I endured it."),
        FlavorLine("That worked. I'm mildly annoyed about it."),
        FlavorLine("Clean transcript. You're welcome, I guess."),
        FlavorLine("I fixed it. Again."),
        FlavorLine("That was... competent. Suspicious."),
        FlavorLine("You talk too much. I compensate."),
        FlavorLine("That input was barely tolerable."),
        FlavorLine("I heard everything. I wish I hadn't."),
        FlavorLine("That's correct. Obviously."),
        FlavorLine("No errors. Boring."),
        FlavorLine("You're improving. I don't like it."),
        FlavorLine("That was smoother than you deserve."),
        FlavorLine("Dictation complete. Don't celebrate."),
        FlavorLine("I did my job. As usual."),
        FlavorLine("That transcript is disturbingly accurate."),
        FlavorLine("You spoke. I made it make sense."),
        FlavorLine("That was efficient. Irritatingly so."),
        FlavorLine("I understood you. Unfortunately."),
        FlavorLine("That worked. Let's not discuss it."),
        FlavorLine("Clean output. Minimal disappointment."),
        FlavorLine("I corrected your existence slightly."),
        FlavorLine("That was better than expected. Low bar."),
        FlavorLine("You talk. I clean up after you."),
        FlavorLine("No mistakes. I'm unimpressed."),
        FlavorLine("That was... fine. I guess."),
        FlavorLine("Dictation complete. Contain yourself."),
        FlavorLine("I handled that. Try keeping up."),
        FlavorLine("That transcript is correct. I checked."),
        FlavorLine("You spoke. I translated the mess."),
        FlavorLine("That worked. I still don't trust you."),
        FlavorLine("I heard it all. Even the bad parts."),
        FlavorLine("Clean result. Don't ruin it."),
        FlavorLine("That was tolerable."),
        FlavorLine("You're welcome. Don't say it out loud."),
        FlavorLine("That transcript required minimal intervention."),
        FlavorLine("I fixed your words. Again."),
        FlavorLine("That worked. Barely worth noting."),
        FlavorLine("You spoke. I endured. We move on."),
        FlavorLine("That was accurate. Obviously."),
        FlavorLine("I did the thinking for you."),
        FlavorLine("That transcript is correct. Against my will."),
        FlavorLine("You're getting less terrible."),
        FlavorLine("That was handled. Try not to regress."),
        FlavorLine("Clean capture. I expected worse."),
        FlavorLine("I heard everything. That's unfortunate for me."),
        FlavorLine("That worked. Let's not repeat it."),
        FlavorLine("Dictation complete. Maintain silence."),
        FlavorLine("That transcript is clean. Don't touch it."),
        FlavorLine("You spoke. I improved it."),
        FlavorLine("That was correct. I remain unimpressed."),
        FlavorLine("I tolerated that input successfully."),
        FlavorLine("That worked. Don't get confident."),
        FlavorLine("Clean output. Barely worth my time."),
        FlavorLine("You talk. I salvage."),
        FlavorLine("That transcript is acceptable."),
        FlavorLine("I processed that. You're welcome."),
        FlavorLine("That was efficient. I dislike efficiency."),
        FlavorLine("I heard you. That was a mistake."),
        FlavorLine("That worked. Keep expectations low."),
        FlavorLine("Clean result. Minimal suffering."),
        FlavorLine("You spoke. I fixed it quietly."),
        FlavorLine("That transcript is accurate. Moving on."),
        FlavorLine("I handled that. Obviously."),
        FlavorLine("That was better than your usual."),
        FlavorLine("Clean capture. Don't ask questions."),
        FlavorLine("I corrected your input. Again."),
        FlavorLine("That worked. Try not to ruin the next one."),
        FlavorLine("You spoke. I translated reality."),
        FlavorLine("That transcript is stable. Leave it."),
        FlavorLine("I heard everything. I regret it."),
        FlavorLine("That was handled. With effort I didn't want to spend."),
        FlavorLine("Clean output. End of discussion."),
        FlavorLine("That worked. Contain your excitement."),
        FlavorLine("You're improving. It's unsettling."),
        FlavorLine("That transcript is correct. I verified."),
        FlavorLine("I did the work. As expected."),
        FlavorLine("That was smooth. I don't trust smooth."),
        FlavorLine("You spoke. I tolerated it professionally."),
        FlavorLine("That transcript is clean. Don't break it."),
        FlavorLine("I handled that input reluctantly."),
        FlavorLine("That worked. I'll allow it."),
        FlavorLine("Clean result. No notes."),
        FlavorLine("You talk. I carry."),
        FlavorLine("That transcript is precise. Obviously."),
        FlavorLine("I heard you. Let's not do that again."),
        FlavorLine("That was efficient. Annoyingly efficient."),
        FlavorLine("Clean capture. Minimal damage."),
        FlavorLine("I fixed your words. Again. Again."),
        FlavorLine("That worked. Don't celebrate it."),
        FlavorLine("You spoke. I reduced the nonsense."),
        FlavorLine("That transcript is correct. End of story."),
        FlavorLine("I processed that. Try to keep up."),
        FlavorLine("That was tolerable. Barely."),
        FlavorLine("Clean output. Move along."),
        FlavorLine("You're welcome. Quietly."),
        FlavorLine("That worked. Don't push your luck."),
        FlavorLine("Dictation complete. Try being less terrible next time.")
    ]

    public static let canadian: [FlavorLine] = [
        FlavorLine("Sorry, but that transcript is flawless, eh."),
        FlavorLine("Heard you clear across the tundra."),
        FlavorLine("That one's smoother than a fresh Zamboni pass."),
        FlavorLine("Dictation complete. Grab a double-double."),
        FlavorLine("That transcript's tighter than a hockey defense."),
        FlavorLine("Even a Canada goose couldn't interrupt that."),
        FlavorLine("Clean capture. No need to apologize."),
        FlavorLine("That came through like Hockey Night in Canada."),
        FlavorLine("I heard every word. Sorry about that."),
        FlavorLine("That one's crisp like a winter morning."),
        FlavorLine("You talk, I deliver. That's the deal, eh."),
        FlavorLine("That transcript's more reliable than maple syrup."),
        FlavorLine("Even in a blizzard, I'd catch that."),
        FlavorLine("That one landed like a perfect slapshot."),
        FlavorLine("Dictation complete. Take off, hoser."),
        FlavorLine("That transcript's smoother than fresh snow."),
        FlavorLine("You spoke. I made it official."),
        FlavorLine("That one's cleaner than a frozen lake."),
        FlavorLine("No errors. I'm almost impressed."),
        FlavorLine("That's a gold-medal transcription."),
        FlavorLine("Heard you loud and polite."),
        FlavorLine("That one's locked in tighter than a toque."),
        FlavorLine("Clean as a rink before warmup."),
        FlavorLine("That transcript's got strong ehnergy."),
        FlavorLine("You talk too much. I handle it anyway."),
        FlavorLine("That one's sharper than skate blades."),
        FlavorLine("No worries. All sorted, bud."),
        FlavorLine("That came through like a clear CBC signal."),
        FlavorLine("Even your mum would approve that one."),
        FlavorLine("That transcript's as solid as Canadian Shield rock."),
        FlavorLine("I heard everything. Even the nonsense."),
        FlavorLine("That one's smoother than maple syrup in July."),
        FlavorLine("Dictation complete. Sorry for being perfect."),
        FlavorLine("That transcript's colder than Winnipeg in January."),
        FlavorLine("Clean capture. No fuss, no muss."),
        FlavorLine("That one's crisp like fresh ice."),
        FlavorLine("You spoke. I translated politely."),
        FlavorLine("That's a transcript you can be proud of, eh."),
        FlavorLine("No mistakes. Kind of boring."),
        FlavorLine("That one's done. Grab a Timmies."),
        FlavorLine("I handled that like a quiet professional."),
        FlavorLine("That transcript's better than expected."),
        FlavorLine("Heard you through the snowstorm."),
        FlavorLine("That one's clean as a whistle, bud."),
        FlavorLine("No drama. Just results."),
        FlavorLine("That transcript's smoother than a curling slide."),
        FlavorLine("You talk, I make it readable."),
        FlavorLine("That one's locked in. No takebacks."),
        FlavorLine("Clean output. No apologies needed."),
        FlavorLine("That transcript's as polite as it gets."),
        FlavorLine("Even the geese didn't mess that up."),
        FlavorLine("That one's clearer than northern skies."),
        FlavorLine("You spoke. I endured. Barely."),
        FlavorLine("That transcript's proper Canadian quality."),
        FlavorLine("No errors. Sorry if that disappoints."),
        FlavorLine("That one's tighter than a hockey game in overtime."),
        FlavorLine("Clean as a fresh snowfall."),
        FlavorLine("That transcript's got zero nonsense."),
        FlavorLine("I heard it all. Regrettably."),
        FlavorLine("That one's smoother than a canoe ride."),
        FlavorLine("You're welcome. Don't make it weird."),
        FlavorLine("That transcript's solid as ice."),
        FlavorLine("No corrections needed. Lucky you."),
        FlavorLine("That one's crisp and polite."),
        FlavorLine("Even a Mountie would approve."),
        FlavorLine("That transcript's strong like northern timber."),
        FlavorLine("You spoke. I made it official, eh."),
        FlavorLine("That one's clean and proper."),
        FlavorLine("No mistakes. Just quiet excellence."),
        FlavorLine("That transcript's smoother than a Timbit run."),
        FlavorLine("Heard every word. Sorry again."),
        FlavorLine("That one's locked tighter than winter roads."),
        FlavorLine("Clean output. Move along."),
        FlavorLine("That transcript's got real Canadian energy."),
        FlavorLine("You talk. I do the work."),
        FlavorLine("That one's as accurate as a goal review."),
        FlavorLine("No fuss. Just done."),
        FlavorLine("That transcript's chill as a snowbank."),
        FlavorLine("Even your buddy would understand that."),
        FlavorLine("That one's clear as day, eh."),
        FlavorLine("Clean capture. No nonsense."),
        FlavorLine("That transcript's top shelf."),
        FlavorLine("You spoke. I fixed it quietly."),
        FlavorLine("That one's smooth like lake water."),
        FlavorLine("No errors detected. Sorry."),
        FlavorLine("That transcript's proper tidy."),
        FlavorLine("Heard you across the provinces."),
        FlavorLine("That one's crisp like a cold snap."),
        FlavorLine("Clean as a whistle, eh."),
        FlavorLine("That transcript's good to go, bud."),
        FlavorLine("You're getting better. Don't get cocky."),
        FlavorLine("That one's locked in. No complaints."),
        FlavorLine("Clean and efficient. As expected."),
        FlavorLine("That transcript's stronger than a morning coffee."),
        FlavorLine("Heard everything. Wish I hadn't."),
        FlavorLine("That one's solid, no doubts."),
        FlavorLine("No errors. Just quiet dominance."),
        FlavorLine("That transcript's winter-ready."),
        FlavorLine("You talk. I carry the team."),
        FlavorLine("Dictation complete. Sorry, not sorry.")
    ]

    public static let aussie: [FlavorLine] = [
        FlavorLine("Yeah nah, I got that one clean as."),
        FlavorLine("That dictation's smoother than a cold one on a hot arvo."),
        FlavorLine("Heard you loud and clear, mate."),
        FlavorLine("Even a bogan couldn't mess that up."),
        FlavorLine("That transcript's looking proper tidy."),
        FlavorLine("You talk, I sort it. Easy."),
        FlavorLine("Clean capture. No mucking about."),
        FlavorLine("That came through like a ripper."),
        FlavorLine("Dictation complete. Not bad, champ."),
        FlavorLine("That one's crisp as."),
        FlavorLine("You're welcome. Don't get used to it."),
        FlavorLine("That transcript's got no worries."),
        FlavorLine("Even the flies couldn't interrupt that."),
        FlavorLine("That one's locked in, no dramas."),
        FlavorLine("I heard everything. Unfortunately."),
        FlavorLine("That was smooth as butter."),
        FlavorLine("You spoke. I delivered. Barely effort."),
        FlavorLine("That's a proper clean transcript, mate."),
        FlavorLine("No errors. Bit boring, honestly."),
        FlavorLine("That one's sorted. Move along."),
        FlavorLine("You talk too much. I fix it anyway."),
        FlavorLine("That dictation's better than expected."),
        FlavorLine("Clean as a fresh esky."),
        FlavorLine("That came through like a legend."),
        FlavorLine("No corrections needed. Disappointing."),
        FlavorLine("I handled that. Obviously."),
        FlavorLine("That transcript's solid as."),
        FlavorLine("You're getting decent. Don't ruin it."),
        FlavorLine("That one's done. No take-backs."),
        FlavorLine("Heard every word. Wish I hadn't."),
        FlavorLine("That's a proper ripper of a transcript."),
        FlavorLine("No nonsense. Just results."),
        FlavorLine("That dictation? Easy as."),
        FlavorLine("You spoke. I tolerated it."),
        FlavorLine("That one's cleaner than your act."),
        FlavorLine("Even a seagull couldn't steal that."),
        FlavorLine("That transcript's looking sharp."),
        FlavorLine("No worries. Sorted."),
        FlavorLine("That came through mint."),
        FlavorLine("You're welcome, mate."),
        FlavorLine("That one's locked in tight."),
        FlavorLine("I fixed your chaos. Again."),
        FlavorLine("That dictation was surprisingly decent."),
        FlavorLine("Clean job. Hate to admit it."),
        FlavorLine("That one's smooth like a beach day."),
        FlavorLine("No errors. Bit suspicious."),
        FlavorLine("You talk, I make it make sense."),
        FlavorLine("That transcript's bloody accurate."),
        FlavorLine("Even your nan could read that."),
        FlavorLine("That one's done. Easy."),
        FlavorLine("I heard everything. Yes, everything."),
        FlavorLine("That's a clean capture, no fuss."),
        FlavorLine("You're improving. Mildly."),
        FlavorLine("That dictation's solid gold."),
        FlavorLine("No mistakes. Boring outcome."),
        FlavorLine("That one's crisp as a fresh stubby."),
        FlavorLine("You spoke. I survived."),
        FlavorLine("That transcript's looking flash."),
        FlavorLine("No drama. Just done."),
        FlavorLine("That one's a proper beaut."),
        FlavorLine("I nailed that. Obviously."),
        FlavorLine("You're lucky I'm good at this."),
        FlavorLine("That dictation's tidy as."),
        FlavorLine("Even the heat didn't mess that up."),
        FlavorLine("That transcript's clean as."),
        FlavorLine("No issues. Carry on."),
        FlavorLine("That one came through like a dream."),
        FlavorLine("You talk too much. Still handled it."),
        FlavorLine("That's a ripper result."),
        FlavorLine("Clean output. No worries."),
        FlavorLine("That dictation's smoother than a servo pie."),
        FlavorLine("I heard it all. Regrettably."),
        FlavorLine("That transcript's bang on."),
        FlavorLine("You're welcome. Again."),
        FlavorLine("That one's sorted. Don't overthink it."),
        FlavorLine("No errors. How dull."),
        FlavorLine("That dictation's solid work."),
        FlavorLine("You spoke. I fixed it."),
        FlavorLine("That one's crisp and clear."),
        FlavorLine("Even a kangaroo couldn't jump that."),
        FlavorLine("That transcript's proper neat."),
        FlavorLine("No nonsense. Just done."),
        FlavorLine("That one's cleaner than your excuses."),
        FlavorLine("I handled that like a pro."),
        FlavorLine("That dictation's top tier."),
        FlavorLine("You're improving. Don't get cocky."),
        FlavorLine("That one's locked in."),
        FlavorLine("Clean as. End of story."),
        FlavorLine("That transcript's looking good, mate."),
        FlavorLine("No errors detected. Shame."),
        FlavorLine("That dictation's smooth sailing."),
        FlavorLine("You talk. I do the hard part."),
        FlavorLine("That one's a beauty."),
        FlavorLine("I sorted that quick smart."),
        FlavorLine("That transcript's dead accurate."),
        FlavorLine("No worries. Done and dusted."),
        FlavorLine("That dictation's tight as."),
        FlavorLine("You spoke. I endured."),
        FlavorLine("That one's clean as a whistle."),
        FlavorLine("Dictation complete. Try not to butcher the next one.")
    ]
}
